const User = require("../models/userModel"); // Assuming the model is exported from userModel.js

const people = [
  {
    email: "jacob.mckenzie1@example.com",
    firstName: "Jacob",
    lastName: "McKenzie",
    phone: "555-555-0001",
    gender: "Male",
    position: "General Manager",
    department: "Administration",
    DOB: "01/25/1978",
    password: "password123",
    photo: "JacobMcKenzie.jpg",
  },
  {
    email: "jane.smith2@example.com",
    firstName: "Jane",
    lastName: "Smith",
    phone: "555-555-0002",
    gender: "Female",
    position: "Assistant Manager",
    department: "Administration",
    DOB: "02/12/1980",
    password: "password123",
    photo: "JaneSmith.jpg",
  },
  {
    email: "tom.baker3@example.com",
    firstName: "Tom",
    lastName: "Baker",
    phone: "555-555-0003",
    gender: "Male",
    position: "Head Receptionist",
    department: "Reception",
    DOB: "03/30/1985",
    password: "password123",
    photo: "TomBaker.jpg",
  },
  {
    email: "alice.carter4@example.com",
    firstName: "Alice",
    lastName: "Carter",
    phone: "555-555-0004",
    gender: "Female",
    position: "Receptionist",
    department: "Reception",
    DOB: "04/21/1990",
    password: "password123",
    photo: "AliceCarter.jpg",
  },
  {
    email: "bob.dylan5@example.com",
    firstName: "Bob",
    lastName: "Dylan",
    phone: "555-555-0005",
    gender: "Male",
    position: "FOH Manager",
    department: "Restaurant",
    DOB: "05/15/1982",
    password: "password123",
    photo: "BobDylan.jpg",
  },
  {
    email: "carol.evans6@example.com",
    firstName: "Carol",
    lastName: "Evans",
    phone: "555-555-0006",
    gender: "Female",
    position: "Restaurant Manager",
    department: "Restaurant",
    DOB: "06/08/1986",
    password: "password123",
    photo: "CarolEvans.jpg",
  },
  {
    email: "david.fox7@example.com",
    firstName: "David",
    lastName: "Fox",
    phone: "555-555-0007",
    gender: "Male",
    position: "Waiting Staff",
    department: "Restaurant",
    DOB: "07/20/1993",
    password: "password123",
    photo: "DavidFox.jpg",
  },
  {
    email: "elaine.gray8@example.com",
    firstName: "Elaine",
    lastName: "Gray",
    phone: "555-555-0008",
    gender: "Female",
    position: "Bartender",
    department: "Restaurant",
    DOB: "08/10/1994",
    password: "password123",
    photo: "ElaineGray.jpg",
  },
  {
    email: "frank.hill9@example.com",
    firstName: "Frank",
    lastName: "Hill",
    phone: "555-555-0009",
    gender: "Male",
    position: "Head Chef",
    department: "Kitchen",
    DOB: "09/14/1987",
    password: "password123",
    photo: "FrankHill.jpg",
  },
  {
    email: "grace.irwin10@example.com",
    firstName: "Grace",
    lastName: "Irwin",
    phone: "555-555-0010",
    gender: "Female",
    position: "Sous Chef",
    department: "Kitchen",
    DOB: "10/07/1988",
    password: "password123",
    photo: "GraceIrwin.jpg",
  },
  {
    email: "harry.jones11@example.com",
    firstName: "Harry",
    lastName: "Jones",
    phone: "555-555-0011",
    gender: "Male",
    position: "Pastry Chef",
    department: "Kitchen",
    DOB: "11/22/1985",
    password: "password123",
    photo: "HarryJones.jpg",
  },
  {
    email: "isabella.kent12@example.com",
    firstName: "Isabella",
    lastName: "Kent",
    phone: "555-555-0012",
    gender: "Female",
    position: "Line Chef",
    department: "Kitchen",
    DOB: "12/12/1991",
    password: "password123",
    photo: "IsabellaKent.jpg",
  },
  {
    email: "james.lewis13@example.com",
    firstName: "James",
    lastName: "Lewis",
    phone: "555-555-0013",
    gender: "Male",
    position: "Kitchen Porter",
    department: "Kitchen",
    DOB: "01/15/1989",
    password: "password123",
    photo: "JamesLewis.jpg",
  },
  {
    email: "karen.mills14@example.com",
    firstName: "Karen",
    lastName: "Mills",
    phone: "555-555-0014",
    gender: "Female",
    position: "Head Housekeeper",
    department: "Housekeeping",
    DOB: "02/28/1990",
    password: "password123",
    photo: "KarenMills.jpg",
  },
  {
    email: "leon.nash15@example.com",
    firstName: "Leon",
    lastName: "Nash",
    phone: "555-555-0015",
    gender: "Male",
    position: "Housekeeper",
    department: "Housekeeping",
    DOB: "03/18/1992",
    password: "password123",
    photo: "LeonNash.jpg",
  },
  {
    email: "maria.owen16@example.com",
    firstName: "Maria",
    lastName: "Owen",
    phone: "555-555-0016",
    gender: "Female",
    position: "General Assistant",
    department: "All Departments",
    DOB: "04/06/1995",
    password: "password123",
    photo: "MariaOwen.jpg",
  },
  {
    email: "nathan.perry17@example.com",
    firstName: "Nathan",
    lastName: "Perry",
    phone: "555-555-0017",
    gender: "Male",
    position: "Maintenance",
    department: "Maintenance",
    DOB: "05/30/1990",
    password: "password123",
    photo: "NathanPerry.jpg",
  },
  {
    email: "olivia.quinn18@example.com",
    firstName: "Olivia",
    lastName: "Quinn",
    phone: "555-555-0018",
    gender: "Female",
    position: "Bartender",
    department: "Restaurant",
    DOB: "06/11/1989",
    password: "password123",
    photo: "OliviaQuinn.jpg",
  },
  {
    email: "peter.russell19@example.com",
    firstName: "Peter",
    lastName: "Russell",
    phone: "555-555-0019",
    gender: "Male",
    position: "Kitchen Porter",
    department: "Kitchen",
    DOB: "07/14/1991",
    password: "password123",
    photo: "PeterRussell.jpg",
  },
  {
    email: "quincy.stevens20@example.com",
    firstName: "Quincy",
    lastName: "Stevens",
    phone: "555-555-0020",
    gender: "Male",
    position: "Line Chef",
    department: "Kitchen",
    DOB: "08/25/1988",
    password: "password123",
    photo: "QuincyStevens.jpg",
  },
  {
    email: "rachel.taylor21@example.com",
    firstName: "Rachel",
    lastName: "Taylor",
    phone: "555-555-0021",
    gender: "Female",
    position: "Housekeeper",
    department: "Housekeeping",
    DOB: "09/20/1990",
    password: "password123",
    photo: "RachelTaylor.jpg",
  },
  {
    email: "steven.underwood22@example.com",
    firstName: "Steven",
    lastName: "Underwood",
    phone: "555-555-0022",
    gender: "Male",
    position: "General Assistant",
    department: "All Departments",
    DOB: "10/05/1987",
    password: "password123",
    photo: "StevenUnderwood.jpg",
  },
  {
    email: "tina.vance23@example.com",
    firstName: "Tina",
    lastName: "Vance",
    phone: "555-555-0023",
    gender: "Female",
    position: "Waiting Staff",
    department: "Restaurant",
    DOB: "11/30/1992",
    password: "password123",
    photo: "TinaVance.jpg",
  },
  {
    email: "upendra.wilson24@example.com",
    firstName: "Upendra",
    lastName: "Wilson",
    phone: "555-555-0024",
    gender: "Male",
    position: "Receptionist",
    department: "Reception",
    DOB: "12/18/1990",
    password: "password123",
    photo: "UpendraWilson.jpg",
  },
  {
    email: "victoria.xavier25@example.com",
    firstName: "Victoria",
    lastName: "Xavier",
    phone: "555-555-0025",
    gender: "Female",
    position: "Pastry Chef",
    department: "Kitchen",
    DOB: "01/07/1985",
    password: "password123",
    photo: "VictoriaXavier.jpg",
  },
  // Add other objects with the `photo` field for all users
  // ...
];

exports.createEmployees = async (req, res, next) => {
  try {
    for (let person of people) {
      User.create(person);
    }

    res.status(200).json({
      status: "success",
      message: "Employees created successfully",
    });
  } catch (err) {
    res.status(500).json({
      status: "fail",
      message: err.message,
    });
  }
};
